"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var FulltimeEmp_1 = require("./FulltimeEmp");
var ContractorEmp_1 = require("./ContractorEmp");
var ControllerEmp_1 = require("./ControllerEmp");
var Teo = new FulltimeEmp_1.default("Teo");
console.log("Teo Salary: ".concat(Teo.getSalary()));
var Ti = new FulltimeEmp_1.default("Ti");
console.log("Ti Salary: ".concat(Ti.getSalary()));
var Tun = new FulltimeEmp_1.default("Tun");
console.log("Tun Salary: ".concat(Tun.getSalary()));
var Dao = new ContractorEmp_1.default("Dao");
console.log("Dao Salary: ".concat(Dao.getSalary()));
var Mai = new ContractorEmp_1.default("Mai");
console.log("Mai Salary: ".concat(Mai.getSalary()));
var totalSalary = new ControllerEmp_1.default().calTotalSalary([Teo, Ti, Tun, Dao, Mai]);
console.log("Total salary: ".concat(totalSalary));
var minSalaryEmp = new ControllerEmp_1.default().getMinSalaryEmp([Teo, Ti, Tun, Dao, Mai]);
console.log("".concat(minSalaryEmp.getName(), " with min salary: ").concat(minSalaryEmp.getSalary()));
var maxSalaryEmp = new ControllerEmp_1.default().getMaxSalaryEmp([Teo, Ti, Tun, Dao, Mai]);
console.log("".concat(maxSalaryEmp.getName(), " with max salary: ").concat(maxSalaryEmp.getSalary()));
;
var sortedEmp = new ControllerEmp_1.default().sortBySalaryASC([Teo, Ti, Tun, Dao, Mai]);
console.log(sortedEmp);
var sortBySalaryDES = new ControllerEmp_1.default().sortBySalaryDES([Teo, Ti, Tun, Dao, Mai]);
console.log(sortBySalaryDES);
